Repository Hala-s-World/Hala-sWorld-SOEN341_Project_W25, pull requests merged in 2025-02, with the labels that each got.

#16 Document Sprint 1 Meeting Minutes
  Meeting Minutes/Meeting_Minutes_24-01-2025.md
  Meeting Minutes/Meeting_Minutes_31-01-2025.md
Labels: documentation

#20 Add Project README
  README.md
Labels: documentation

#18 Role based authentication
  src/pages/Dashboard.jsx
  src/store/authStore.js
Labels: enhancement

#21 Css styling for login
  src/App.jsx
  src/assets/components/AuthenticationForm.jsx
  src/assets/components/Banner.jsx
  src/assets/components/Login.jsx
  src/assets/components/LoginOverlay.jsx
  src/assets/components/Register.jsx
  src/assets/fonts/DMSans-VariableFont_opsz,wght.ttf
  src/assets/fonts/Gochi_Hand/GochiHand-Regular.ttf
  src/assets/fonts/Gochi_Hand/OFL.txt
  src/assets/fonts/Good Matcha.otf
  src/assets/media/cat.jpg
  src/assets/media/logo.png
  src/assets/styles/Authentication.css
  src/pages/LoginPage.jsx
Labels: enhancement

#22 Fix logo position
  src/assets/styles/Authentication.css
Labels: enhancement

#26 Implement homepage structure, CSS styling, and animations (US#14)
  src/App.jsx
  src/assets/styles/homepage.css
  src/pages/Homepage.jsx
Labels: enhancement, UI/UX

#40 Added all necessary methods for database manipulation for our applica…
  .gitignore
  src/App.jsx
  src/assets/components/AuthenticationForm.jsx
  src/assets/components/Login.jsx
  src/assets/components/Register.jsx
  src/helper/supabaseAPI.js
  src/pages/LoginPage.jsx
Labels: enhancement
