Repository Hala-s-World/Hala-sWorld-SOEN341_Project_W25, pull requests merged in 2025-03, with the labels that each got.

#49 Sprint 2 Meeting Minutes (February 7 & 14, 2025)
  Meeting Minutes/Meeting_Minutes_07-02-2025.md
  Meeting Minutes/Meeting_Minutes_14-02-2025.md
Labels: documentation

#50 Implement real-time messages updates (#US 16.3)
  Meeting Minutes/Meeting_Minutes_07-02-2025.md
  Meeting Minutes/Meeting_Minutes_14-02-2025.md
Labels: Task

#58 Restore Supabase Database Schema
  src/helper/supabaseClient.js
Labels: bug, backend

#60 transfered supabase policies to new project and fixed the login and r…
  src/App.jsx
  src/assets/components/AuthenticationForm.jsx
  src/assets/components/Register.jsx
  src/assets/components/SideBar.jsx
  src/helper/supabaseAPI.js
  src/store/authStore.js
Labels: bug, backend

#69 Realtime presence tracking
  package-lock.json
  package.json
  sprint_planning (version 1).xlsx
  sprint_planning.xlsx
  src/App.jsx
  src/assets/components/AuthenticationForm.jsx
  src/assets/components/FriendCard.jsx
  src/assets/components/GetFriendStatus.jsx
  src/assets/components/GetUserStatus.jsx
  src/assets/components/Register.jsx
  src/assets/components/SideBar.jsx
  src/helper/supabaseAPI.js
  src/store/authStore.js
Labels: Task

#77 68 us184 enable sending messages to offline users
  src/assets/components/DirectMessaging.jsx
  src/assets/components/FriendCard.jsx
  src/assets/components/GetUserStatus.jsx
  src/assets/components/LastSeen.jsx
  src/assets/components/UnreadCount.jsx
  src/assets/styles/unreadCount.css
  src/helper/supabaseAPI.js
Labels: Task

#79 CI workflow using **GitHub Actions**
  workflows/dev-run.yml
Labels: CI/CD

#81 Create Basic Example Test File for CI Pipeline
  tests/example.test.js
Labels: CI/CD

#84 Add Unit Tests for LoginPage and Homepage Components
  tests/Homepage.test.jsx
  tests/LoginPage.test.jsx
Labels: Unit Test
